name = "turnip"
main = "src/index.ts"
compatibility_date = "2024-03-14"
compatibility_flags = ["nodejs_compat"]


[dev]
port = 3000

[[d1_databases]]
binding = "db"
database_name = "turnip"
database_id = ""
